# Generated by Django 4.0.1 on 2022-05-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('apdate', models.DateTimeField()),
                ('city', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('son_name', models.CharField(max_length=80)),
                ('writer', models.CharField(max_length=80)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.singer')),
            ],
        ),
    ]
