# Generated by Django 4.0.1 on 2022-05-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Son',
            new_name='Song',
        ),
    ]
