# Generated by Django 4.0.1 on 2022-05-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_alter_song_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
