# Generated by Django 4.0.1 on 2022-05-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=70)),
                ('boolean', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=60)),
                ('desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=70)),
                ('boolean', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
